apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: tk-comp-java-1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/christianvogt-tenant/tk-test/tk-comp-java-1@sha256:6809ec6bf16eb4e5c742fc5fb0531c169cddb34623d52e96fea761f09e40f16d
        name: my-java-springboot
        resources: {}
status: {}
