apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tk-comp-java-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tk-comp-java-1
    app.kubernetes.io/part-of: tk-test
  name: tk-comp-java-1kp4t
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tk-comp-java-1
    weight: 100
status: {}
